# Generated by Django 4.2.7 on 2025-05-24 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Tarefa')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('status', models.CharField(choices=[('PEND', 'Pendente'), ('FAZE', 'Sendo feita'), ('CONC', 'Concluída'), ('CANC', 'Cancelada')], default='PEND', max_length=4, verbose_name='Status')),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta'), (4, 'Urgente')], default=2, verbose_name='Prioridade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_prevista_conclusao', models.DateField(blank=True, null=True, verbose_name='Prazo de Entrega')),
                ('data_conclusao_efetiva', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão Efetiva')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('atribuido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído Por')),
                ('voluntario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_atribuidas', to='voluntarios.voluntario', verbose_name='Voluntário Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-prioridade', 'data_prevista_conclusao', 'titulo'],
            },
        ),
    ]
