# Generated by Django 4.2.9 on 2025-06-07 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0003_alter_beneficiario_escolaridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=200, verbose_name='Nome do Curso')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(verbose_name='Data de Conclusão')),
                ('data_emissao_certificado', models.DateField(blank=True, null=True, verbose_name='Data de Emissão do Certificado')),
                ('certificado_recebido', models.BooleanField(default=False, verbose_name='Certificado Físico Recebido')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='beneficiarios.beneficiario', verbose_name='Beneficiário')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-data_conclusao', 'beneficiario__nome_completo'],
                'unique_together': {('beneficiario', 'curso', 'data_conclusao')},
            },
        ),
    ]
