# Generated by Django 4.2.7 on 2025-05-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('NI', 'Não Informado')], default='NI', max_length=2, verbose_name='Gênero')),
                ('cpf', models.CharField(blank=True, help_text='Formato: XXX.XXX.XXX-XX (Opcional)', max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, help_text='(Opcional)', max_length=20, null=True, verbose_name='RG')),
                ('cep', models.CharField(blank=True, help_text='Formato: XXXXX-XXX', max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero_endereco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento_endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('telefone_principal', models.CharField(blank=True, help_text='Formato: (XX) XXXXX-XXXX', max_length=20, null=True, verbose_name='Telefone Principal')),
                ('telefone_secundario', models.CharField(blank=True, help_text='(Opcional)', max_length=20, null=True, verbose_name='Telefone Secundário')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('escolaridade', models.CharField(choices=[('FI', 'Fundamental Incompleto'), ('FC', 'Fundamental Completo'), ('MI', 'Médio Incompleto'), ('MC', 'Médio Completo'), ('SI', 'Superior Incompleto'), ('SC', 'Superior Completo'), ('PG', 'Pós-graduação'), ('NI', 'Não Informado')], default='NI', max_length=2, verbose_name='Escolaridade')),
                ('ocupacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupação/Profissão')),
                ('renda_familiar_aproximada', models.DecimalField(blank=True, decimal_places=2, help_text='Valor em Reais. Ex: 1500.50', max_digits=10, null=True, verbose_name='Renda Familiar Mensal Aproximada (R$)')),
                ('como_conheceu_ong', models.TextField(blank=True, null=True, verbose_name='Como conheceu a ONG?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Beneficiário',
                'verbose_name_plural': 'Beneficiários',
                'ordering': ['nome_completo'],
            },
        ),
    ]
