# Generated by Django 4.2.9 on 2025-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Inativação'),
        ),
    ]
