# Generated by Django 4.2.9 on 2025-06-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_beneficiario_data_inativacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='escolaridade',
            field=models.CharField(choices=[('FI', 'Fundamental Incompleto'), ('FC', 'Fundamental Completo'), ('MI', 'Médio Incompleto'), ('MC', 'Médio Completo'), ('NI', 'Não Informado')], default='NI', max_length=2, verbose_name='Escolaridade'),
        ),
    ]
