# Generated by Django 4.2.9 on 2025-06-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0006_voluntario_data_inativacao'),
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='voluntario_responsavel',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='voluntarios_responsaveis',
            field=models.ManyToManyField(blank=True, related_name='tarefas_responsaveis', to='voluntarios.voluntario', verbose_name='Voluntários Responsáveis'),
        ),
    ]
