# Generated by Django 4.2.7 on 2025-05-24 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(help_text='Formato: XXX.XXX.XXX-XX', max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, help_text='Formato: (XX) XXXXX-XXXX', max_length=20, null=True, verbose_name='Telefone Celular')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço Completo')),
                ('areas_interesse', models.TextField(blank=True, help_text='Descreva as áreas em que o voluntário tem interesse em atuar.', null=True, verbose_name='Áreas de Interesse')),
                ('disponibilidade', models.TextField(blank=True, help_text='Ex: Segundas e Quartas à tarde, Finais de semana.', null=True, verbose_name='Disponibilidade')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.OneToOneField(help_text='Conta de usuário associada a este voluntário.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
                'ordering': ['nome_completo'],
            },
        ),
    ]
