# Generated by Django 4.2.9 on 2025-05-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='endereco',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='cep',
            field=models.CharField(blank=True, help_text='Formato: XXXXX-XXX', max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='complemento_endereco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='numero_endereco',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
    ]
