# Generated by Django 4.2.9 on 2025-05-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0002_remove_voluntario_endereco_voluntario_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='disponibilidade',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_dom_m',
            field=models.BooleanField(default=False, verbose_name='Domingo (Manhã)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_dom_n',
            field=models.BooleanField(default=False, verbose_name='Domingo (Noite)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_dom_t',
            field=models.BooleanField(default=False, verbose_name='Domingo (Tarde)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_qua_m',
            field=models.BooleanField(default=False, verbose_name='Quarta (Manhã)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_qua_n',
            field=models.BooleanField(default=False, verbose_name='Quarta (Noite)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_qua_t',
            field=models.BooleanField(default=False, verbose_name='Quarta (Tarde)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_qui_m',
            field=models.BooleanField(default=False, verbose_name='Quinta (Manhã)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_qui_n',
            field=models.BooleanField(default=False, verbose_name='Quinta (Noite)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_qui_t',
            field=models.BooleanField(default=False, verbose_name='Quinta (Tarde)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_sab_m',
            field=models.BooleanField(default=False, verbose_name='Sábado (Manhã)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_sab_n',
            field=models.BooleanField(default=False, verbose_name='Sábado (Noite)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_sab_t',
            field=models.BooleanField(default=False, verbose_name='Sábado (Tarde)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_seg_m',
            field=models.BooleanField(default=False, verbose_name='Segunda (Manhã)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_seg_n',
            field=models.BooleanField(default=False, verbose_name='Segunda (Noite)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_seg_t',
            field=models.BooleanField(default=False, verbose_name='Segunda (Tarde)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_sex_m',
            field=models.BooleanField(default=False, verbose_name='Sexta (Manhã)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_sex_n',
            field=models.BooleanField(default=False, verbose_name='Sexta (Noite)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_sex_t',
            field=models.BooleanField(default=False, verbose_name='Sexta (Tarde)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_ter_m',
            field=models.BooleanField(default=False, verbose_name='Terça (Manhã)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_ter_n',
            field=models.BooleanField(default=False, verbose_name='Terça (Noite)'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='disp_ter_t',
            field=models.BooleanField(default=False, verbose_name='Terça (Tarde)'),
        ),
    ]
