# Generated by Django 4.2.9 on 2025-06-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0003_remove_voluntario_disponibilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='rg',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RG'),
        ),
    ]
