# Generated by Django 4.2.9 on 2025-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0005_alter_voluntario_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Inativação'),
        ),
    ]
