# Generated by Django 4.2.9 on 2025-06-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0004_voluntario_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='rg',
            field=models.CharField(default='000000000', max_length=10, verbose_name='RG'),
            preserve_default=False,
        ),
    ]
